name: Update XBPS Repository

on:
  push:
    paths:
      - "x86_64/*.xbps"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install XBPS tools
        run: |
          git clone https://github.com/void-linux/xbps
          cd xbps
          ./configure
          make -j$(nproc)
          sudo make install

      - name: Fix permissions
        run: chmod +x vscripts/update_repo.sh

      - name: Update repo metadata
        run: bash vscripts/update_repo.sh

      - name: Generate HTML index
        run: python3 vscripts/autogen.py

      - name: Commit changes
        run: |
          git config --global user.name "t4n-bot"
          git config --global user.email "bot@t4nos.dev"

          git add .
          git commit -m "auto update repository" || echo "no changes"
          git push